site_name: Terraform Modules Documentation

docs_dir: docs

theme:
  name: readthedocs

nav:
  - Home: index.md
  - eks: eks/README.md
  - eks-ebs-csi-driver: eks-ebs-csi-driver/README.md
  - eks-external-secrets: eks-external-secrets/README.md
  - eks-karpenter: eks-karpenter/README.md
  - eks-kube-prometheus-stack: eks-kube-prometheus-stack/README.md
  - eks-load-balancer-controller: eks-load-balancer-controller/README.md
  - eks-rbac-default-roles: eks-rbac-default-roles/README.md
  - eks-velero: eks-velero/README.md
  - terraform-state-management: terraform-state-management/README.md
  - vpc: vpc/README.md

